//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSe.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<int> lab { get; set; }
        public Nullable<int> subject_teacher_id { get; set; }
    
        public virtual Subject_Teacher Subject_Teacher { get; set; }
    }
}
